---
apiVersion: admissioncontroller.config.gardener.cloud/v1alpha1
kind: AdmissionControllerConfiguration
gardenClientConnection:
  qps: 100
  burst: 130
server:
  https:
    bindAddress: 0.0.0.0
    port: 2721
    tls:
      serverCertDir: dev/tls/gardener-admission-controller
  resourceAdmissionConfiguration:
    limits:
    - apiGroups: ["core.gardener.cloud"]
      apiVersions: ["*"]
      resources: ["shoots", "plants"]
      size: 100k
    unrestrictedSubjects:
    - kind: Group
      name: gardener.cloud:system:seeds
      apiGroup: rbac.authorization.k8s.io
    operationMode: block
