apiVersion: {{ include "rbacversion" . }}
kind: ClusterRoleBinding
metadata:
  name: gardener-resource-manager-seed
  labels:
    app: gardener-resource-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener-resource-manager-seed
subjects:
- kind: ServiceAccount
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
